import { useRef, useState, type MouseEvent } from 'react';
import { useQuery } from '@tanstack/react-query';
import { api, ApiError, type AlertDetail, type InterventionView, type Period, type ProcessingStatus, type User } from '../../lib/api';
import { EmptyState, ErrorState, EvaluationBadge, LoadingState, PageHeader, RiskBadge } from '../../components/ui';
import { dateLabel, reasonLabel, timestampLabel } from '../../lib/format';
import { ActivityEditForm, AlertStateForm, PlanActivityForm } from './FollowupForms';
import { AlertStatusBadge, InterventionStatusBadge, interventionKindLabels } from './labels';
import './features.css';

type Props = { user: User; period: Period | null; processing: ProcessingStatus | null; alertId: string; onNavigate: (path: string) => void };
export function AlertDetailPage(props: Props) {
  if (props.user.role === 'RESEARCHER') return <EmptyState title="Consulta no disponible para tu rol"><p>Los casos están reservados al personal autorizado.</p></EmptyState>;
  if (!props.period) return <><PageHeader title="Caso de seguimiento" /><EmptyState title="Selecciona un periodo"><p>El caso se consulta dentro de un contexto autorizado.</p></EmptyState></>;
  return <CaseRecord key={`${props.user.id}:${props.user.role}:${props.period.id}:${props.alertId}`} {...props} period={props.period} />;
}

function CaseRecord({ user, period, processing, alertId, onNavigate }: Props & { period: Period }) {
  const detail = useQuery({ queryKey: [user.id, user.role, 'alert', period.id, alertId], queryFn: ({ signal }) => api.alert(alertId, signal), retry: false });
  const back = `/alertas?period_id=${encodeURIComponent(period.id)}`;
  const link = (event: MouseEvent<HTMLAnchorElement>, path: string) => { if (event.button === 0 && !event.ctrlKey && !event.metaKey && !event.altKey && !event.shiftKey) { event.preventDefault(); onNavigate(path); } };
  const backAction = <a className="button secondary" href={back} onClick={event => link(event, back)}>← Volver a alertas</a>;
  async function refresh(): Promise<AlertDetail | null> { const result = await detail.refetch(); return result.isSuccess ? result.data : null; }
  if (detail.isPending) return <><PageHeader title="Caso de seguimiento" action={backAction} /><LoadingState label="Consultando el caso…" /></>;
  if (detail.isError && (!detail.data || detail.error instanceof ApiError && [403, 404].includes(detail.error.status))) return <><PageHeader title="Caso de seguimiento" action={backAction} />{detail.error instanceof ApiError && [403, 404].includes(detail.error.status) ? <EmptyState title="Este caso no está disponible"><p>Consulta los casos autorizados del periodo seleccionado.</p></EmptyState> : <ErrorState error={detail.error} onRetry={() => void detail.refetch()} />}</>;
  const data = detail.data!; const alert = data.alert;
  if (alert.period_id !== period.id) return <><PageHeader title="Caso de seguimiento" action={backAction} /><EmptyState title="Este caso no está disponible en el periodo seleccionado"><p>Vuelve a la lista para consultar el contexto elegido.</p></EmptyState></>;
  const writer = user.role === 'ADMIN' || user.role === 'TUTOR';
  const globalWrite = Boolean(processing?.operations.write_followup.available) && !period.is_locked && period.data_origin === 'SYNTHETIC' && !detail.isError;
  const commonBlocked = period.is_locked ? reasonLabel('PERIOD_LOCKED') : period.data_origin !== 'SYNTHETIC' ? reasonLabel('INSTITUTIONAL_PROCESSING_NOT_READY') : detail.isError ? 'No pudimos actualizar la consulta. Conservamos tu borrador; consulta el caso otra vez antes de escribir.' : !processing ? 'No pudimos consultar la disponibilidad. Las escrituras permanecen deshabilitadas.' : reasonLabel(processing.operations.write_followup.reason);
  const caseBlocked = !globalWrite ? commonBlocked : reasonLabel(alert.capabilities.reason);
  const studentPath = `/estudiantes/${alert.student_id}?period_id=${encodeURIComponent(period.id)}&section_id=${encodeURIComponent(alert.section_id)}`;
  const current = data.latest_snapshot && data.latest_prediction?.snapshot_id === data.latest_snapshot.id ? data.latest_prediction : null;
  return <div className="followup-feature"><PageHeader title={`Caso de ${alert.anon_code}`} eyebrow="SEGUIMIENTO DE SIMULACIÓN" description={`${alert.grade}.º / ${alert.section_code} · Periodo ${period.code}. Acciones internas con datos sintéticos; no se envían comunicaciones.`} action={backAction} />
    {detail.isError && <ErrorState error={detail.error} onRetry={() => void detail.refetch()} />}
    <div className="followup-grid"><section className="panel"><h2>Motivo y fuente del caso</h2><RiskBadge risk={alert.severity} /><p className="muted followup-note">Una evaluación media o alta motivó este seguimiento. Esta fuente conserva la evidencia y puede diferir de la evaluación actual.</p><dl className="followup-fields"><div><dt>Apertura del caso</dt><dd>{timestampLabel(alert.opened_at)}</dd></div><div><dt>Corte que motivó el caso</dt><dd>{timestampLabel(data.source_prediction.cutoff_at)}</dd></div><div><dt>Evaluación de la fuente</dt><dd>{timestampLabel(data.source_prediction.predicted_at)}</dd></div><div><dt>Fecha objetivo de la fuente</dt><dd>{dateLabel(data.source_prediction.target_date)}</dd></div></dl></section>
      <section className="panel"><h2>Evaluación actual</h2><EvaluationBadge status={alert.current_evaluation_status} /><RiskBadge risk={alert.current_evaluation_status === 'EVALUATED' ? alert.current_risk_level : null} /><dl className="followup-fields" style={{ marginTop: 20 }}><div><dt>Último corte disponible</dt><dd>{timestampLabel(alert.latest_cutoff_at)}</dd></div><div><dt>Evaluación actual registrada</dt><dd>{timestampLabel(current?.predicted_at)}</dd></div></dl><p className="muted followup-note">{alert.current_evaluation_status === 'NOT_EVALUATED' ? 'La revisión actual sigue pendiente. Una evaluación anterior no se atribuye a nuevos datos. El caso previo se conserva para revisión humana.' : alert.current_evaluation_status === 'INSUFFICIENT_DATA' ? 'La revisión actual tiene datos insuficientes. No se inventa riesgo bajo; el seguimiento previo permanece disponible.' : alert.current_risk_level === 'LOW' ? 'El riesgo actual es bajo. El caso se conserva y requiere una decisión humana para concluirlo o descartarlo.' : 'Revisa los datos y planifica la actividad que corresponda a esta simulación.'}</p><a className="followup-link" href={studentPath} onClick={event => link(event, studentPath)}>Consultar datos e historial del estudiante →</a></section></div>
    <section className="panel"><h2>Responsable y estado</h2><dl className="followup-fields"><div><dt>Responsable</dt><dd>{alert.assigned_display_name ?? 'Sin tutor asignado'}</dd></div><div><dt>Estado del caso</dt><dd><AlertStatusBadge status={alert.status} /></dd></div><div><dt>Última actualización operativa</dt><dd>{timestampLabel(alert.updated_at)}</dd></div><div><dt>Cierre registrado</dt><dd>{alert.closed_at ? timestampLabel(alert.closed_at) : 'Caso sin cerrar'}</dd></div></dl>{alert.resolution_reason && <><h3>Motivo de cierre registrado</h3><p className="muted">{alert.resolution_reason}</p></>}
      {writer ? <AlertStateForm user={user} alert={alert} available={globalWrite && alert.capabilities.can_edit} blocked={caseBlocked} onRefresh={refresh} /> : <p className="muted followup-note">Tu rol permite consultar este seguimiento. Los cambios corresponden al tutor autorizado o al administrador.</p>}
    </section>
    <section className="panel"><div className="followup-section-heading"><h2>Actividades de seguimiento</h2><span className="badge">{data.interventions.length} registradas</span></div><p className="muted" style={{ marginBottom: 22 }}>Planificada no significa realizada. Solo la actividad con estado “Realizada” y fecha efectiva explícita cuenta como tal. Un caso cerrado conserva sus actividades pendientes.</p>{data.interventions.length === 0 ? <EmptyState title="Todavía no hay actividades"><p>Planifica una actividad desde este caso activo para registrar el seguimiento de simulación.</p></EmptyState> : <ul className="followup-interventions">{data.interventions.map(intervention => <ActivityRecord key={intervention.id} user={user} intervention={intervention} canWrite={writer && globalWrite} blocked={!globalWrite ? commonBlocked : reasonLabel(intervention.edit_block_reason)} onRefresh={refresh} />)}</ul>}</section>
    {writer && <section className="panel"><PlanActivityForm user={user} alert={alert} available={globalWrite && alert.capabilities.can_plan} blocked={caseBlocked} onRefresh={refresh} /></section>}
    <section className="panel"><h2>Historial del caso</h2><p className="muted" style={{ marginBottom: 15 }}>Aperturas y cambios efectivos registrados como evidencia. Las horas operativas actuales se muestran en Lima; los cortes pertenecen al calendario sintético del estudio.</p>{data.history.length ? <ol className="followup-history">{data.history.map(event => <li key={event.id}><time dateTime={event.occurred_at}>{timestampLabel(event.occurred_at)}</time><p>{event.summary}</p></li>)}</ol> : <EmptyState title="Sin eventos de seguimiento"><p>Los cambios efectivos aparecerán cuando se registren.</p></EmptyState>}{data.history_truncated && <p className="notice">Este panel muestra los eventos recientes. <a href={studentPath} className="followup-link" onClick={event => link(event, studentPath)}>Consulta el historial paginado del estudiante</a> para revisar la evidencia completa.</p>}</section>
  </div>;
}

function ActivityRecord({ user, intervention, canWrite, blocked, onRefresh }: { user: User; intervention: InterventionView; canWrite: boolean; blocked: string; onRefresh: () => Promise<AlertDetail | null> }) {
  const [editing, setEditing] = useState(false);
  const trigger = useRef<HTMLButtonElement>(null);
  const heading = useRef<HTMLDivElement>(null);
  const available = canWrite && intervention.can_edit;
  return <li><div className="followup-intervention-heading"><h3>{interventionKindLabels[intervention.kind]}</h3><InterventionStatusBadge status={intervention.status} /></div><p>{intervention.objective}</p><dl className="followup-fields"><div><dt>Fecha programada</dt><dd>{timestampLabel(intervention.scheduled_at)}</dd></div><div><dt>Fecha efectiva</dt><dd>{intervention.performed_at ? timestampLabel(intervention.performed_at) : 'No realizada'}</dd></div><div><dt>Registrada</dt><dd>{timestampLabel(intervention.created_at)}</dd></div><div><dt>Actualización</dt><dd>{timestampLabel(intervention.updated_at)}</dd></div></dl>{intervention.notes && <p>{intervention.notes}</p>}{(user.role === 'ADMIN' || user.role === 'TUTOR') && intervention.status === 'PLANNED' && !editing && <div className="followup-actions"><button ref={trigger} className="button secondary" type="button" disabled={!available} onClick={() => { setEditing(true); requestAnimationFrame(() => heading.current?.querySelector<HTMLElement>('select')?.focus()); }}>Registrar actividad</button>{!available && <p className="muted">{blocked}</p>}</div>}
    {editing && <div ref={heading}><ActivityEditForm user={user} intervention={intervention} available={available} blocked={intervention.status === 'DONE' || intervention.status === 'CANCELLED' ? 'Esta actividad ya está cerrada y conserva su evidencia. No admite nuevas ediciones.' : blocked} onRefresh={onRefresh} onClose={() => { setEditing(false); requestAnimationFrame(() => trigger.current?.focus()); }} /></div>}
  </li>;
}
