import type { Period, ProcessingStatus, Section, User } from '../../lib/api';
import { EmptyState, PageHeader } from '../../components/ui';
import { dateLabel, reasonLabel } from '../../lib/format';
export function HomePage({ user, period, sections, processing, onNavigate }: { user: User; period: Period | null; sections: Section[]; processing: ProcessingStatus | null; onNavigate: (path: string) => void }) {
  if (user.role === 'RESEARCHER') return <><PageHeader eyebrow="INICIO" title="Tu espacio de consulta" description="Alcance general del estudio y sesión de investigador." /><section className="panel"><h2>Acceso de investigador</h2><p>Tu rol de investigador no tiene acceso al contexto escolar.</p><p className="muted">Puedes conocer el alcance general y cerrar tu sesión. El acceso a registros, modelos o futuras exportaciones requiere una autorización específica.</p><span className="badge">Sesión activa · Investigador</span></section></>;
  return <><PageHeader eyebrow="INICIO" title="Un contexto claro para consultar" description="Elige un periodo y revisa información generada para comprobar el sistema." />
    {!period ? <EmptyState title="No hay un periodo disponible"><p>El administrador debe preparar un contexto autorizado. No se muestran estudiantes ni estimaciones sin periodo.</p></EmptyState> : <section className="panel home-context"><div><p className="eyebrow">PERIODO DE CONSULTA</p><h2>{period.code}</h2><p>{dateLabel(period.start_date)} — {dateLabel(period.end_date)}</p><p className="muted">Año {period.school_year} · {period.is_locked ? 'Bloqueado para escrituras' : 'Abierto'} · {period.data_origin === 'SYNTHETIC' ? 'Datos sintéticos' : 'Contexto institucional sin procesamiento'}</p></div><div><span className="badge">{sections.length} secciones autorizadas</span><p className="muted">{user.role === 'TUTOR' ? 'Solo las asignadas a tu cuenta.' : 'Alcance devuelto por el servidor.'}</p></div></section>}
    <section className="home-actions" aria-label="Qué puedes hacer"><article className="orientation"><span className="orientation-number">01</span><h2>Consultar estudiantes</h2><p>Compara observaciones y abre el detalle para revisar cortes e historial.</p><button className="button primary" type="button" disabled={!period || !sections.length} onClick={() => onNavigate('/estudiantes')}>Ver estudiantes →</button>{!sections.length && <small>No hay secciones asignadas en este periodo. Consulta al administrador.</small>}</article>
      {user.role === 'ADMIN' && <><article className="orientation"><span className="orientation-number">02</span><h2>Importar un archivo registrado</h2><p>Prepara, revisa y confirma únicamente el CSV sintético verificado.</p><button className="button secondary" type="button" disabled={!period || !processing?.operations.import.available || period.data_origin !== 'SYNTHETIC'} onClick={() => onNavigate('/datos')}>Ir a Datos →</button>{!processing?.operations.import.available && <small>{reasonLabel(processing?.operations.import.reason)}</small>}</article><article className="orientation"><span className="orientation-number">03</span><h2>Revisar modelos</h2><p>Consulta el modelo registrado y evalúa el periodo cuando esté disponible.</p><button className="button secondary" type="button" onClick={() => onNavigate('/modelos')}>Consultar modelos →</button></article></>}
    </section><section className="panel learning-note"><h2>Observación y estimación son diferentes</h2><div className="learning-grid"><div><h3>Sin evaluar</h3><p>El corte actual todavía no tiene una predicción vigente. No significa riesgo bajo.</p></div><div><h3>Datos insuficientes</h3><p>Faltan variables requeridas para estimar. Los valores ausentes se conservan sin inventar datos.</p></div><div><h3>Una simulación, con límites</h3><p>Comparar modelos con datos generados comprueba software. No valida su rendimiento en estudiantes reales.</p></div></div></section>
  </>;
}
