/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disponibilidad del proceso
         * @description No revelar configuración ni secretos.
         */
        get: operations["live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Disponibilidad de base de datos
         * @description 200 si la base está disponible; 503 en caso contrario.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Comprobar Origin, limitar intentos y validar credenciales. Usar cookie de sesión; sin registro público.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar usuario actual
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener CSRF ligado a la sesión (HMAC determinista)
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revocar sesión
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar periodos configurados; lista vacia antes de configuracion
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["periods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar secciones autorizadas del año del periodo
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["sections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar estudiantes autorizados
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["students"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar seguimiento del estudiante
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["studentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar historial
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["studentTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validar CSV y crear vista previa
         * @description Bloqueado con 422 INSTITUTIONAL_PROCESSING_NOT_READY hasta implementar procedencia autorizada, escala, periodo, ventanas, fechas y calidad. Exige sesion ADMIN y CSRF. No persiste archivos ni registros escolares. Motor preservado: UTF-8, 5 MiB, 10000 filas, transaccion, idempotencia, revision inmutable y expected_preview_version.
         */
        post: operations["previewImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar lote y errores
         * @description Autorizacion en servidor por rol y seccion. Origen institucional; no habilita procesamiento.
         */
        get: operations["importDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/imports/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar lote sin errores
         * @description Bloqueado con 422 INSTITUTIONAL_PROCESSING_NOT_READY hasta implementar procedencia autorizada, escala, periodo, ventanas, fechas y calidad. Exige sesion ADMIN y CSRF. No persiste archivos ni registros escolares. Motor preservado: UTF-8, 5 MiB, 10000 filas, transaccion, idempotencia, revision inmutable y expected_preview_version.
         */
        post: operations["commitImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * listModels
         * @description Modelos paginados; orden created_at descendente e id ascendente. Lista vacía en activo. Sin hashes, rutas, particiones ni métricas privadas.
         */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * modelDetail
         * @description Metadatos públicos sanitizados. No activa ni descarga modelos.
         */
        get: operations["modelDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * predictionDetail
         * @description TUTOR solo su sección. Inexistente o ajena devuelve 404. No sustituye riesgo faltante por LOW.
         */
        get: operations["predictionDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * runPredictions
         * @description Orden: sesión, rol, CSRF, protocolo, cuerpo, periodo/modelo. En S3 devuelve bloqueo 422 incluso con cuerpo inválido después de CSRF; nunca procesa información institucional. Núcleo aislado: última revisión incorporada/disponible hasta as_of, abstención sin fila, reutilización snapshot/model y auditoría atómica. Modelo no disponible: 409 posterior al protocolo. Sin entrenamiento HTTP ni alertas.
         */
        post: operations["runPredictions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            code: string;
            message: string;
            details: {
                field?: string | null;
                row?: number | null;
                message: string;
            }[];
            /** Format: uuid */
            request_id: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        User: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** @enum {string} */
            role: "ADMIN" | "TUTOR" | "DIRECTOR" | "RESEARCHER";
        };
        LoginInput: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResult: {
            user: components["schemas"]["User"];
            csrf_token: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            expires_at: string;
        };
        Csrf: {
            csrf_token: string;
        };
        Period: {
            /** Format: uuid */
            id: string;
            code: string;
            school_year: number;
            /** Format: date */
            start_date: string;
            /** Format: date */
            end_date: string;
            /** @enum {string} */
            data_origin: "REAL";
            is_locked: boolean;
        };
        Section: {
            /** Format: uuid */
            id: string;
            code: string;
            grade: number;
            school_year: number;
            /** Format: uuid */
            tutor_id: string | null;
        };
        Snapshot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            period_id: string;
            /** @enum {string} */
            data_origin: "REAL";
            /** Format: date */
            window_start: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            cutoff_at: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            available_at: string;
            /** Format: date */
            target_date: string;
            revision: number;
            /**
             * Format: uuid
             * @description Revisión anterior del mismo corte y matrícula; null en la primera.
             */
            supersedes_id: string | null;
            average_grade: number | null;
            attendance_pct: number | null;
            activities_pct: number | null;
            participation_level: number | null;
            behavior_incidents: number | null;
            age_years: number | null;
            missing_fraction: number;
        };
        /** @description Probabilidades todas null o todas presentes; suma 1 con tolerancia 0.00001. Validar suma en servidor. calibrated true exige valores presentes. */
        Prediction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            snapshot_id: string;
            /** Format: uuid */
            model_id: string;
            /** @enum {string} */
            data_origin: "REAL";
            /** @enum {string} */
            risk_level: "LOW" | "MEDIUM" | "HIGH";
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            cutoff_at: string;
            /** Format: date */
            target_date: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            predicted_at: string;
            probability_low: number | null;
            probability_medium: number | null;
            probability_high: number | null;
            probabilities_calibrated: boolean;
        } & (({
            probability_low?: null;
            probability_medium?: null;
            probability_high?: null;
        } | {
            probability_low?: number;
            probability_medium?: number;
            probability_high?: number;
        }) & unknown);
        Student: {
            /** Format: uuid */
            id: string;
            anon_code: string;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            period_id: string;
            /** Format: uuid */
            section_id: string;
            section_code: string;
            grade: number;
            /** @enum {string} */
            data_origin: "REAL";
            average_grade: number | null;
            attendance_pct: number | null;
            /** Format: date-time */
            latest_cutoff_at: string | null;
            /** @enum {string|null} */
            risk_level: "LOW" | "MEDIUM" | "HIGH" | null;
            /** @enum {string} */
            evaluation_status: "EVALUATED" | "NOT_EVALUATED" | "INSUFFICIENT_DATA";
            /** Format: uuid */
            active_alert_id: string | null;
        };
        StudentDetail: {
            student: components["schemas"]["Student"];
            latest_snapshot: components["schemas"]["Snapshot"] | null;
            latest_prediction: components["schemas"]["Prediction"] | null;
            alerts: components["schemas"]["Alert"][];
            interventions: components["schemas"]["Intervention"][];
        };
        TimelineEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            event_type: "SNAPSHOT" | "PREDICTION" | "ALERT" | "INTERVENTION";
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            occurred_at: string;
            summary: string;
            /** Format: uuid */
            entity_id: string;
        };
        ImportError: {
            row: number;
            column: string;
            code: string;
            message: string;
        };
        ImportBatch: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            period_id: string;
            /** @enum {string} */
            data_origin: "REAL";
            file_name: string;
            file_sha256: string;
            schema_version: string;
            /** @enum {string} */
            status: "PREVIEW" | "READY" | "COMMITTED" | "FAILED";
            total_rows: number;
            valid_rows: number;
            invalid_rows: number;
            planned_students: number;
            planned_enrollments: number;
            planned_snapshots: number;
            preview_version: number;
            errors: components["schemas"]["ImportError"][];
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            created_at: string;
            /** Format: date-time */
            committed_at: string | null;
        };
        ImportCommit: {
            /** Format: uuid */
            batch_id: string;
            /** @enum {string} */
            status: "COMMITTED";
            created_snapshots: number;
            reused_result: boolean;
        };
        Alert: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            student_id: string;
            anon_code: string;
            /** Format: uuid */
            prediction_id: string;
            /** @enum {string} */
            data_origin: "REAL";
            /** @enum {string} */
            severity: "MEDIUM" | "HIGH";
            /** @enum {string} */
            status: "OPEN" | "IN_REVIEW" | "RESOLVED" | "DISMISSED";
            /** Format: uuid */
            assigned_to: string | null;
            resolution_reason: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            opened_at: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            updated_at: string;
            /** Format: date-time */
            closed_at: string | null;
            version: number;
        };
        Intervention: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            alert_id: string | null;
            /** @enum {string} */
            data_origin: "REAL";
            /** @enum {string} */
            kind: "TUTORING" | "REINFORCEMENT" | "FAMILY_MEETING" | "OTHER";
            objective: string;
            /** @enum {string} */
            status: "PLANNED" | "DONE" | "CANCELLED";
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            scheduled_at: string;
            /** Format: date-time */
            performed_at: string | null;
            notes: string | null;
            version: number;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            created_at: string;
            /**
             * Format: date-time
             * @description RFC 3339 con zona obligatoria; respuesta normalizada a UTC (Z).
             */
            updated_at: string;
        };
        StudentPage: {
            items: components["schemas"]["Student"][];
            total: number;
            page: number;
            page_size: number;
        };
        TimelineEventPage: {
            items: components["schemas"]["TimelineEvent"][];
            total: number;
            page: number;
            page_size: number;
        };
        /** Model */
        Model: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Algorithm
             * @enum {string}
             */
            algorithm: "DUMMY" | "RANDOM_FOREST" | "SVM" | "XGBOOST";
            /**
             * Data Origin
             * @constant
             */
            data_origin: "REAL";
            /** Feature Schema Version */
            feature_schema_version: string;
            /** Reference Criterion Version */
            reference_criterion_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "EVALUATED" | "APPROVED" | "RETIRED";
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelPage */
        ModelPage: {
            /** Items */
            items: components["schemas"]["Model"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PredictionRunInput */
        PredictionRunInput: {
            /**
             * Period Id
             * Format: uuid
             */
            period_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
        };
        /** Abstention */
        Abstention: {
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "MODEL_NOT_AVAILABLE" | "INSUFFICIENT_DATA" | "INELIGIBLE" | "INCOMPATIBLE";
            /** Reason */
            reason: string;
        };
        /** PredictionRunResult */
        PredictionRunResult: {
            /**
             * Period Id
             * Format: uuid
             */
            period_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Model Id
             * Format: uuid
             */
            model_id: string;
            /** Selected */
            selected: number;
            /** Created */
            created: number;
            /** Reused */
            reused: number;
            /** Abstentions */
            abstentions: components["schemas"]["Abstention"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Base de datos no disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    /** @description sesión HttpOnly; SameSite=Lax; Path=/; Secure en HTTPS. La cookie no se devuelve en JSON. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResult"];
                };
            };
            /** @description Credenciales inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Origen de solicitud no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de integridad o concurrencia; resolver el estado y reintentar. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Límite de intentos excedido */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Csrf"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header: {
                /** @description Token CSRF ligado a la sesión; validarlo en servidor. */
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada; borrar cookie */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    periods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Period"][];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sections: {
        parameters: {
            query: {
                period_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"][];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    students: {
        parameters: {
            query: {
                period_id: string;
                section_id?: string;
                page?: number;
                page_size?: number;
                search?: string;
                risk_level?: "LOW" | "MEDIUM" | "HIGH";
                sort?: "anon_code" | "risk_desc" | "updated_desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentPage"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    studentDetail: {
        parameters: {
            query: {
                period_id: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetail"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    studentTimeline: {
        parameters: {
            query: {
                period_id: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimelineEventPage"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    previewImport: {
        parameters: {
            query?: never;
            header: {
                /** @description Token CSRF ligado a la sesión; validarlo en servidor. */
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** Format: uuid */
                    period_id: string;
                };
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Operación completada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    importDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatch"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    commitImport: {
        parameters: {
            query?: never;
            header: {
                /** @description Token CSRF ligado a la sesión; validarlo en servidor. */
                "X-CSRF-Token": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    expected_preview_version: number;
                };
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportCommit"];
                };
            };
            /** @description Sesión inválida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rol, alcance o CSRF no permitido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto de versión, periodo bloqueado o modelo no disponible */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Entrada invalida, origen no admitido o INSTITUTIONAL_PROCESSING_NOT_READY en escrituras de importacion; sin escrituras escolares. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado; no se exponen detalles de base. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio de base de datos no disponible. Error sanitizado; sin consultas, parametros ni secretos. Los conflictos de integridad se devuelven como errores de dominio 409/422, nunca 503. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listModels: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la operación implementada; ejecución institucional bloqueada en S3. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelPage"];
                };
            };
            /** @description SESSION_INVALID: sesión requerida o revocada. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description FORBIDDEN o CSRF_INVALID; permisos comprobados en servidor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso inexistente o no accesible en la sección; no revela casos ajenos. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description PERIOD_LOCKED, MODEL_NOT_AVAILABLE, MODEL_INCOMPATIBLE, PREDICTION_CONFLICT o INTEGRITY_CONFLICT. Reutilización snapshot/model devuelve resultado existente, no error. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validación, NOT_ELIGIBLE o INSTITUTIONAL_PROCESSING_NOT_READY; sin escrituras académicas. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Base no disponible: Error sanitizado, sin consultas, parámetros ni secretos; nunca para integridad. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    modelDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la operación implementada; ejecución institucional bloqueada en S3. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description SESSION_INVALID: sesión requerida o revocada. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description FORBIDDEN o CSRF_INVALID; permisos comprobados en servidor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso inexistente o no accesible en la sección; no revela casos ajenos. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description PERIOD_LOCKED, MODEL_NOT_AVAILABLE, MODEL_INCOMPATIBLE, PREDICTION_CONFLICT o INTEGRITY_CONFLICT. Reutilización snapshot/model devuelve resultado existente, no error. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validación, NOT_ELIGIBLE o INSTITUTIONAL_PROCESSING_NOT_READY; sin escrituras académicas. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Base no disponible: Error sanitizado, sin consultas, parámetros ni secretos; nunca para integridad. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    predictionDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultado de la operación implementada; ejecución institucional bloqueada en S3. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prediction"];
                };
            };
            /** @description SESSION_INVALID: sesión requerida o revocada. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description FORBIDDEN o CSRF_INVALID; permisos comprobados en servidor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso inexistente o no accesible en la sección; no revela casos ajenos. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description PERIOD_LOCKED, MODEL_NOT_AVAILABLE, MODEL_INCOMPATIBLE, PREDICTION_CONFLICT o INTEGRITY_CONFLICT. Reutilización snapshot/model devuelve resultado existente, no error. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validación, NOT_ELIGIBLE o INSTITUTIONAL_PROCESSING_NOT_READY; sin escrituras académicas. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Base no disponible: Error sanitizado, sin consultas, parámetros ni secretos; nunca para integridad. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    runPredictions: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRunInput"];
            };
        };
        responses: {
            /** @description Resultado de la operación implementada; ejecución institucional bloqueada en S3. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRunResult"];
                };
            };
            /** @description SESSION_INVALID: sesión requerida o revocada. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description FORBIDDEN o CSRF_INVALID; permisos comprobados en servidor. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Recurso inexistente o no accesible en la sección; no revela casos ajenos. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description PERIOD_LOCKED, MODEL_NOT_AVAILABLE, MODEL_INCOMPATIBLE, PREDICTION_CONFLICT o INTEGRITY_CONFLICT. Reutilización snapshot/model devuelve resultado existente, no error. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validación, NOT_ELIGIBLE o INSTITUTIONAL_PROCESSING_NOT_READY; sin escrituras académicas. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Error interno inesperado sanitizado. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Base no disponible: Error sanitizado, sin consultas, parámetros ni secretos; nunca para integridad. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
